import * as Types from '@/graphql/types.generated';

import { Time, Upload } from "./scalars";
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type UserFragment = { __typename?: 'User', id: string, createdAt: Time, updatedAt: Time, username: string, name: string, email: string, phoneNumber: string, landlineNumber?: string | null, role: Types.UserRole, status: Types.UserStatus, type: Types.UserType, agreeEmail: boolean, agreeSMS: boolean, bizInfo?: { __typename?: 'BusinessInfo', bizCEO: string, bizRegNumber: string, bizType: string, bizItem: string, bizZipCode: string, bizAddress1: string, bizAddress2?: string | null, bizLicenseURL?: string | null } | null };

export type BusinessInfoFragment = { __typename?: 'BusinessInfo', bizCEO: string, bizRegNumber: string, bizType: string, bizItem: string, bizZipCode: string, bizAddress1: string, bizAddress2?: string | null, bizLicenseURL?: string | null };

export type LoginMutationVariables = Types.Exact<{
  username: Types.Scalars['String']['input'];
  password: Types.Scalars['String']['input'];
}>;


export type LoginMutation = { __typename?: 'Mutation', login: { __typename?: 'Token', accessToken: string, refreshToken: string } };

export type RegisterMutationVariables = Types.Exact<{
  input: Types.RegisterInput;
}>;


export type RegisterMutation = { __typename?: 'Mutation', register: { __typename?: 'User', id: string, createdAt: Time, updatedAt: Time, username: string, name: string, email: string, phoneNumber: string, landlineNumber?: string | null, role: Types.UserRole, status: Types.UserStatus, type: Types.UserType, agreeEmail: boolean, agreeSMS: boolean, bizInfo?: { __typename?: 'BusinessInfo', bizCEO: string, bizRegNumber: string, bizType: string, bizItem: string, bizZipCode: string, bizAddress1: string, bizAddress2?: string | null, bizLicenseURL?: string | null } | null } };

export type GetMeQueryVariables = Types.Exact<{ [key: string]: never; }>;


export type GetMeQuery = { __typename?: 'Query', me?: { __typename?: 'User', id: string, createdAt: Time, updatedAt: Time, username: string, name: string, email: string, phoneNumber: string, landlineNumber?: string | null, role: Types.UserRole, status: Types.UserStatus, type: Types.UserType, agreeEmail: boolean, agreeSMS: boolean, bizInfo?: { __typename?: 'BusinessInfo', bizCEO: string, bizRegNumber: string, bizType: string, bizItem: string, bizZipCode: string, bizAddress1: string, bizAddress2?: string | null, bizLicenseURL?: string | null } | null } | null };

export const BusinessInfoFragmentDoc = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"BusinessInfo"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"BusinessInfo"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"bizCEO"}},{"kind":"Field","name":{"kind":"Name","value":"bizRegNumber"}},{"kind":"Field","name":{"kind":"Name","value":"bizType"}},{"kind":"Field","name":{"kind":"Name","value":"bizItem"}},{"kind":"Field","name":{"kind":"Name","value":"bizZipCode"}},{"kind":"Field","name":{"kind":"Name","value":"bizAddress1"}},{"kind":"Field","name":{"kind":"Name","value":"bizAddress2"}},{"kind":"Field","name":{"kind":"Name","value":"bizLicenseURL"}}]}}]} as unknown as DocumentNode<Types.BusinessInfoFragment, unknown>;
export const UserFragmentDoc = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"User"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"User"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}},{"kind":"Field","name":{"kind":"Name","value":"updatedAt"}},{"kind":"Field","name":{"kind":"Name","value":"username"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"email"}},{"kind":"Field","name":{"kind":"Name","value":"phoneNumber"}},{"kind":"Field","name":{"kind":"Name","value":"landlineNumber"}},{"kind":"Field","name":{"kind":"Name","value":"role"}},{"kind":"Field","name":{"kind":"Name","value":"status"}},{"kind":"Field","name":{"kind":"Name","value":"type"}},{"kind":"Field","name":{"kind":"Name","value":"agreeEmail"}},{"kind":"Field","name":{"kind":"Name","value":"agreeSMS"}},{"kind":"Field","name":{"kind":"Name","value":"bizInfo"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"BusinessInfo"}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"BusinessInfo"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"BusinessInfo"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"bizCEO"}},{"kind":"Field","name":{"kind":"Name","value":"bizRegNumber"}},{"kind":"Field","name":{"kind":"Name","value":"bizType"}},{"kind":"Field","name":{"kind":"Name","value":"bizItem"}},{"kind":"Field","name":{"kind":"Name","value":"bizZipCode"}},{"kind":"Field","name":{"kind":"Name","value":"bizAddress1"}},{"kind":"Field","name":{"kind":"Name","value":"bizAddress2"}},{"kind":"Field","name":{"kind":"Name","value":"bizLicenseURL"}}]}}]} as unknown as DocumentNode<Types.UserFragment, unknown>;
export const LoginDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"Login"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"username"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"password"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"login"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"username"},"value":{"kind":"Variable","name":{"kind":"Name","value":"username"}}},{"kind":"Argument","name":{"kind":"Name","value":"password"},"value":{"kind":"Variable","name":{"kind":"Name","value":"password"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"accessToken"}},{"kind":"Field","name":{"kind":"Name","value":"refreshToken"}}]}}]}}]} as unknown as DocumentNode<Types.LoginMutation, Types.LoginMutationVariables>;
export const RegisterDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"Register"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"input"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"RegisterInput"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"register"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"Variable","name":{"kind":"Name","value":"input"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"User"}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"User"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"User"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}},{"kind":"Field","name":{"kind":"Name","value":"updatedAt"}},{"kind":"Field","name":{"kind":"Name","value":"username"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"email"}},{"kind":"Field","name":{"kind":"Name","value":"phoneNumber"}},{"kind":"Field","name":{"kind":"Name","value":"landlineNumber"}},{"kind":"Field","name":{"kind":"Name","value":"role"}},{"kind":"Field","name":{"kind":"Name","value":"status"}},{"kind":"Field","name":{"kind":"Name","value":"type"}},{"kind":"Field","name":{"kind":"Name","value":"agreeEmail"}},{"kind":"Field","name":{"kind":"Name","value":"agreeSMS"}},{"kind":"Field","name":{"kind":"Name","value":"bizInfo"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"BusinessInfo"}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"BusinessInfo"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"BusinessInfo"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"bizCEO"}},{"kind":"Field","name":{"kind":"Name","value":"bizRegNumber"}},{"kind":"Field","name":{"kind":"Name","value":"bizType"}},{"kind":"Field","name":{"kind":"Name","value":"bizItem"}},{"kind":"Field","name":{"kind":"Name","value":"bizZipCode"}},{"kind":"Field","name":{"kind":"Name","value":"bizAddress1"}},{"kind":"Field","name":{"kind":"Name","value":"bizAddress2"}},{"kind":"Field","name":{"kind":"Name","value":"bizLicenseURL"}}]}}]} as unknown as DocumentNode<Types.RegisterMutation, Types.RegisterMutationVariables>;
export const GetMeDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"GetMe"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"me"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"User"}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"User"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"User"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}},{"kind":"Field","name":{"kind":"Name","value":"updatedAt"}},{"kind":"Field","name":{"kind":"Name","value":"username"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"email"}},{"kind":"Field","name":{"kind":"Name","value":"phoneNumber"}},{"kind":"Field","name":{"kind":"Name","value":"landlineNumber"}},{"kind":"Field","name":{"kind":"Name","value":"role"}},{"kind":"Field","name":{"kind":"Name","value":"status"}},{"kind":"Field","name":{"kind":"Name","value":"type"}},{"kind":"Field","name":{"kind":"Name","value":"agreeEmail"}},{"kind":"Field","name":{"kind":"Name","value":"agreeSMS"}},{"kind":"Field","name":{"kind":"Name","value":"bizInfo"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"BusinessInfo"}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"BusinessInfo"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"BusinessInfo"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"bizCEO"}},{"kind":"Field","name":{"kind":"Name","value":"bizRegNumber"}},{"kind":"Field","name":{"kind":"Name","value":"bizType"}},{"kind":"Field","name":{"kind":"Name","value":"bizItem"}},{"kind":"Field","name":{"kind":"Name","value":"bizZipCode"}},{"kind":"Field","name":{"kind":"Name","value":"bizAddress1"}},{"kind":"Field","name":{"kind":"Name","value":"bizAddress2"}},{"kind":"Field","name":{"kind":"Name","value":"bizLicenseURL"}}]}}]} as unknown as DocumentNode<Types.GetMeQuery, Types.GetMeQueryVariables>;